Repository fonsp/Pluto.jl, pull requests merged in 2022-10, with the labels that each got.

#2300 Fix method invalidations around `Base.convert`
  src/notebook/Cell.jl
  src/webserver/Dynamic.jl
  src/webserver/Firebasey.jl
Labels: performance

#2298 PlutoPkg: if Pkg.resolve fails, try updating the registries
  src/Pluto.jl
  src/packages/IOListener.jl
  src/packages/Packages.jl
  src/packages/PkgCompat.jl
Labels: enhancement, package manager

#2303 Allow solving multiple definitions by disabling one, attempt 2
  src/analysis/Topology.jl
  src/analysis/topological_order.jl
  src/evaluation/Run.jl
  test/cell_disabling.jl
Labels: backend, reactivity

#2177 Preparations for native Windows app
  frontend/Desktop.d.ts
  frontend/components/Editor.js
  frontend/components/ExportBanner.js
  frontend/components/FilePicker.js
  frontend/components/welcome/Open.js
  frontend/editor.css
  frontend/index.css
  frontend/welcome.css
  src/webserver/Dynamic.jl
  src/webserver/SessionActions.jl
  src/webserver/Static.jl
  tsconfig.json
Labels: frontend, wide audience

#2308 Fixes "UndefVarError: expr not defined" in replace_returns_with_error_in_interpolation
  src/runner/PlutoRunner.jl
Labels: backend, expression explorer

#2273 Automatically disable older cells to solve multiple defs
  frontend/components/Editor.js
  frontend/components/ProgressBar.js
  frontend/components/Scroller.js
  frontend/components/UndoDelete.js
  frontend/editor.css
  src/analysis/Topology.jl
  src/analysis/topological_order.jl
  src/evaluation/Run.jl
  src/webserver/Dynamic.jl
Labels: backend, reactivity

#2329 🐝 Fix nested embed_display, by fixing return values of "nested" <script>
  frontend/components/CellOutput.js
Labels: bug, frontend

#2331 Fix MsgPack for a TypedArray with custom view over a buffer
  frontend/common/MsgPack.js
Labels: bug, frontend

#2338 Don't run `static_resolve_topology()` to detect text cells
  src/evaluation/Run.jl
  test/Analysis.jl
Labels: reactivity, expression explorer, performance
