Repository fonsp/Pluto.jl, pull requests merged in 2022-05, with the labels that each got.

#2077 unresolved_cells: handle Skipped correctly
  src/evaluation/Run.jl
  test/MacroAnalysis.jl
Labels: backend, performance

#2079 `resolve_topology`: maintain identity when nothing changed
  src/analysis/data structures.jl
  src/evaluation/Run.jl
Labels: backend, performance

#2081 Continue CI on error
  .github/workflows/Test.yml
Labels: tests

#2054 Generate precompile directives via PrecompileSignatures.jl
  .github/workflows/Test.yml
  Project.toml
  src/Pluto.jl
  src/webserver/Dynamic.jl
  src/webserver/SessionActions.jl
  src/webserver/WebServer.jl
  test/helpers.jl
  test/runtests.jl
Labels: backend, performance

#2075 Prevent registry update if it is fresh
  src/packages/PkgCompat.jl
  src/webserver/WebServer.jl
Labels: package manager, performance

#2062 Reduce overspecializations in PlutoRunner.format_output
  src/runner/PlutoRunner.jl
Labels: backend, performance

#2073 Performance of state diffing: lazy dictionaries, immutable comparison
  src/webserver/Dynamic.jl
  src/webserver/FirebaseyUtils.jl
Labels: backend, performance

#2098 Slightly reduce TTFX for `SessionActions.open`
  src/analysis/ExpressionExplorer.jl
  src/analysis/topological_order.jl
  src/notebook/Notebook.jl
  src/runner/PlutoRunner.jl
Labels: performance

#2108 ImageShow.jl: disable HTML show method for cell output
  src/runner/PlutoRunner.jl
Labels: other packages, display & PlutoRunner

#2027 Scope log_channel to a single notebook_id
  src/evaluation/WorkspaceManager.jl
  src/runner/PlutoRunner.jl
  test/compiletimes.jl
Labels: logging

#1755 JS API to get/set input value of element like Pluto
  frontend/common/Bond.js
  frontend/components/CellOutput.js
Labels: enhancement, frontend

#2117 Speed up `tree_data_array_elements`
  src/runner/PlutoRunner.jl
Labels: performance

#2115 Display logs from async cell at source
  src/evaluation/WorkspaceManager.jl
Labels: logging

#2128 Handle assignments in parameters expr
  src/analysis/ExpressionExplorer.jl
  test/ExpressionExplorer.jl
Labels: expression explorer

#1995 Allow JS state (`this`) inside DivElement
  frontend/components/CellOutput.js
  frontend/components/TreeView.js
Labels: frontend

#2138 Replace all `Array{T,1}` by `Vector{T}`
  sample/Tower of Hanoi.jl
  src/analysis/ExpressionExplorer.jl
  src/analysis/Parse.jl
  src/runner/PlutoRunner.jl
Labels: backend
