Repository fonsp/Pluto.jl, pull requests merged in 2022-03, with the labels that each got.

#1966 improve support for benchmarktools
  src/analysis/ExpressionExplorer.jl
  src/runner/PlutoRunner.jl
  test/ExpressionExplorer.jl
  test/MacroAnalysis.jl
Labels: reactivity, other packages

#1975 Make css independent of position wrt body
  frontend/components/Editor.js
  frontend/editor.css
Labels: frontend

#1948 🧹 Remove service worker
  frontend/editor.html
  frontend/index.html
  frontend/sw.js
Labels: frontend

#1974 🧹 refactor: Move initialisation code out of Editor component
  frontend/components/Editor.js
  frontend/editor.js
Labels: frontend

#1983 Improve accuracy of compilation benchmarks and add one for `Pluto.run`
  src/webserver/WebServer.jl
  test/compiletimes.jl
  test/helpers.jl
Labels: performance

#1991 Optimize `maybe_macroexpand`
  src/analysis/ExpressionExplorer.jl
  test/ExpressionExplorer.jl
  test/MoreAnalysis.jl
Labels: performance

#1978 🧂 more precompile for dynamic functions!
  src/Configuration.jl
  src/webserver/Dynamic.jl
  src/webserver/MsgPack.jl
  src/webserver/WebServer.jl
Labels: performance
