Repository fonsp/Pluto.jl, pull requests merged in 2025-03, with the labels that each got.

#3017 Update syntax highlighting colors
  frontend/components/CellInput.js
  frontend/editor.css
  frontend/highlightjs.css
  frontend/themes/dark.css
  frontend/themes/light.css
Labels: frontend, CM6

#3161 downstream_recursive and upstream_recursive: don't include initial cells in output
  src/analysis/MoreAnalysis.jl
  test/MoreAnalysis.jl
Labels: backend

#3166 Remove `FileEditEvent` and add `StateChangeEvent` in its place
  src/notebook/Events.jl
  src/webserver/Dynamic.jl
Labels: backend, performance
